/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 册内序号调整
 * @export
 * @interface BookSortIndexDto
 */
export interface BookSortIndexDto {
    /**
     * 客户编号
     * @type {number}
     * @memberof BookSortIndexDto
     */
    custId?: any;
    /**
     * 册内序号
     * @type {number}
     * @memberof BookSortIndexDto
     */
    bookSortIndex?: any;
}
