/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 登录返回
 * @export
 * @interface LogOutput
 */
export interface LogOutput {
    /**
     * AccessToken
     * @type {string}
     * @memberof LogOutput
     */
    accessToken?: any | null;
    /**
     * TokenType
     * @type {string}
     * @memberof LogOutput
     */
    tokenType?: any | null;
}
