/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 登录
 * @export
 * @interface LoginInput
 */
export interface LoginInput {
    /**
     * 机构编码
     * @type {string}
     * @memberof LoginInput
     */
    tenantName: any;
    /**
     * 账号
     * @type {string}
     * @memberof LoginInput
     */
    userName: any;
    /**
     * 密码
     * @type {string}
     * @memberof LoginInput
     */
    passWord: any;
}
