/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 人员信息
 * @export
 * @interface MeterReaderDto
 */
export interface MeterReaderDto {
    /**
     * 人员Id
     * @type {string}
     * @memberof MeterReaderDto
     */
    id?: any;
    /**
     * 姓名
     * @type {string}
     * @memberof MeterReaderDto
     */
    name?: any | null;
}
