/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 账单列表
 * @export
 * @interface PdaChargeListDto
 */
export interface PdaChargeListDto {
    /**
     * 费用编号
     * @type {number}
     * @memberof PdaChargeListDto
     */
    feeId?: any;
    /**
     * 账单年月
     * @type {number}
     * @memberof PdaChargeListDto
     */
    billMonth?: any;
    /**
     * 抄表时间
     * @type {string}
     * @memberof PdaChargeListDto
     */
    readingDate?: any | null;
    /**
     * 上期抄码
     * @type {number}
     * @memberof PdaChargeListDto
     */
    lastReading?: any;
    /**
     * 本期抄码
     * @type {number}
     * @memberof PdaChargeListDto
     */
    reading?: any;
    /**
     * 抄见水量
     * @type {number}
     * @memberof PdaChargeListDto
     */
    readWater?: any;
    /**
     * 开账水量
     * @type {number}
     * @memberof PdaChargeListDto
     */
    billWater?: any;
    /**
     * 账单金额
     * @type {number}
     * @memberof PdaChargeListDto
     */
    extendedAmount?: any;
    /**
     * 违约金
     * @type {number}
     * @memberof PdaChargeListDto
     */
    lateFee?: any;
    /**
     * 账单明细
     * @type {Array&lt;PdaChargeDetails&gt;}
     * @memberof PdaChargeListDto
     */
    chargeDetails?: any | null;
}
