/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 收费统计
 * @export
 * @interface PdaPaymentCollect
 */
export interface PdaPaymentCollect {
    /**
     * 收费日期
     * @type {Date}
     * @memberof PdaPaymentCollect
     */
    payDate?: any;
    /**
     * 实际收费
     * @type {number}
     * @memberof PdaPaymentCollect
     */
    actualMoney?: any;
    /**
     * 实际销账
     * @type {number}
     * @memberof PdaPaymentCollect
     */
    soldMoney?: any;
    /**
     * 预存存入
     * @type {number}
     * @memberof PdaPaymentCollect
     */
    depositIn?: any;
    /**
     * 预存抵扣
     * @type {number}
     * @memberof PdaPaymentCollect
     */
    depositOut?: any;
}
