/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 抄表状态
 * @export
 * @interface PdaReadStateDto
 */
export interface PdaReadStateDto {
    /**
     * 状态编码
     * @type {string}
     * @memberof PdaReadStateDto
     */
    stateCode?: any;
    /**
     * 状态名称
     * @type {string}
     * @memberof PdaReadStateDto
     */
    stateName?: string;
    /**
     * 抄表算法
     * @type {number}
     * @memberof PdaReadStateDto
     */
    meterReadAlgorithm?: any;
    /**
     * 排序
     * @type {number}
     * @memberof PdaReadStateDto
     */
    sort?: any;
    /**
     * 父级Id
     * @type {number}
     * @memberof PdaReadStateDto
     */
    parentId?: any;
    /**
     * 备注
     * @type {string}
     * @memberof PdaReadStateDto
     */
    remark?: any;
    /**
     * 
     * @type {number}
     * @memberof PdaReadStateDto
     */
    id?: any;
}
