/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PdaUserPermissionDto } from "./pda-user-permission-dto";

/**
 * 抄表员个人信息
 * @export
 * @interface PdaMeterReaderDto
 */
export interface PdaMeterReaderDto {
    /**
     * 工号
     * @type {string}
     * @memberof PdaMeterReaderDto
     */
    userName?: any;
    /**
     * 邮箱
     * @type {string}
     * @memberof PdaMeterReaderDto
     */
    email?: any;
    /**
     * 电话
     * @type {string}
     * @memberof PdaMeterReaderDto
     */
    phoneNumber?: any;
    /**
     * Pda权限
     * @type {Array&lt;PdaUserPermissionDto&gt;}
     * @memberof PdaMeterReaderDto
     */
    userPermissions?: PdaUserPermissionDto[];
    /**
     * 人员Id
     * @type {string}
     * @memberof PdaMeterReaderDto
     */
    id?: any;
    /**
     * 姓名
     * @type {string}
     * @memberof PdaMeterReaderDto
     */
    name?: any;
}
