/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PdaPaymentSubtotalPagedResultDto } from "./pda-payment-subtotal-paged-result-dto";

/**
 * 收费明细
 * @export
 * @interface PdaPaySubtotalsDto
 */
export interface PdaPaySubtotalsDto {
    /**
     * 户数
     * @type {number}
     * @memberof PdaPaySubtotalsDto
     */
    custCount?: any;
    /**
     * 实际收费
     * @type {number}
     * @memberof PdaPaySubtotalsDto
     */
    actualMoney?: any;
    /**
     * 实际销账
     * @type {number}
     * @memberof PdaPaySubtotalsDto
     */
    soldMoney?: any;
    /**
     * 
     * @type {PdaPaymentSubtotalPagedResultDto}
     * @memberof PdaPaySubtotalsDto
     */
    paySubtotals?: PdaPaymentSubtotalPagedResultDto;
}
