/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 移动端抄表-客户清单
 * @export
 * @interface PdaReadDataDto
 */
export interface PdaReadDataDto {
    /**
     * 抄表年月
     * @type {number}
     * @memberof PdaReadDataDto
     */
    billMonth?: any;
    /**
     * 客户编号
     * @type {number}
     * @memberof PdaReadDataDto
     */
    custId?: any;
    /**
     * 抄次
     * @type {number}
     * @memberof PdaReadDataDto
     */
    readTimes?: any;
    /**
     * 抄表附件地址
     * @type {Array&lt;TerminalFileDto&gt;}
     * @memberof PdaReadDataDto
     */
    terminalFiles?: any;
    /**
     * 欠费笔数
     * @type {number}
     * @memberof PdaReadDataDto
     */
    oweNumber?: any;
    /**
     * 册本编号
     * @type {number}
     * @memberof PdaReadDataDto
     */
    bookId?: any;
    /**
     * 册本编码
     * @type {string}
     * @memberof PdaReadDataDto
     */
    bookCode?: any;
    /**
     * 册内序号
     * @type {number}
     * @memberof PdaReadDataDto
     */
    bookSortIndex?: any;
    /**
     * 客户编号
     * @type {string}
     * @memberof PdaReadDataDto
     */
    custCode?: any;
    /**
     * 客户名称
     * @type {string}
     * @memberof PdaReadDataDto
     */
    custName?: any;
    /**
     * 客户地址
     * @type {string}
     * @memberof PdaReadDataDto
     */
    custAddress?: any;
    /**
     * 客户状态
     * @type {string}
     * @memberof PdaReadDataDto
     */
    custState?: any;
    /**
     * 预存款余额
     * @type {number}
     * @memberof PdaReadDataDto
     */
    deposit?: any;
    /**
     * 上次零头
     * @type {number}
     * @memberof PdaReadDataDto
     */
    lastChange?: any;
    /**
     * 用水性质
     * @type {number}
     * @memberof PdaReadDataDto
     */
    priceCode?: any;
    /**
     * 水表状态
     * @type {string}
     * @memberof PdaReadDataDto
     */
    meterState?: any;
    /**
     * 水表条形码
     * @type {string}
     * @memberof PdaReadDataDto
     */
    barCode?: any;
    /**
     * 水表钢印号
     * @type {string}
     * @memberof PdaReadDataDto
     */
    steelMark?: any;
    /**
     * 水表位置
     * @type {string}
     * @memberof PdaReadDataDto
     */
    installLocation?: any;
    /**
     * 口径
     * @type {number}
     * @memberof PdaReadDataDto
     */
    caliberValue?: any;
    /**
     * 量程
     * @type {number}
     * @memberof PdaReadDataDto
     */
    rangeValue?: any;
    /**
     * 上次抄码
     * @type {number}
     * @memberof PdaReadDataDto
     */
    lastReading?: any;
    /**
     * 上次子表抄码
     * @type {number}
     * @memberof PdaReadDataDto
     */
    lastChildReading?: any;
    /**
     * 上次抄见水量
     * @type {number}
     * @memberof PdaReadDataDto
     */
    lastReadWater?: any;
    /**
     * 上次抄表时间
     * @type {Date}
     * @memberof PdaReadDataDto
     */
    lastReadDate?: any;
    /**
     * 上次抄表状态
     * @type {number}
     * @memberof PdaReadDataDto
     */
    lastReadStateId?: any;
    /**
     * 本次抄码
     * @type {number}
     * @memberof PdaReadDataDto
     */
    reading?: any;
    /**
     * 本次子表抄码
     * @type {number}
     * @memberof PdaReadDataDto
     */
    childReading?: any;
    /**
     * 本次抄见水量
     * @type {number}
     * @memberof PdaReadDataDto
     */
    readWater?: any;
    /**
     * 本次抄表时间
     * @type {Date}
     * @memberof PdaReadDataDto
     */
    readDate?: any;
    /**
     * 抄表状态
     * @type {number}
     * @memberof PdaReadDataDto
     */
    readStateId?: any;
    /**
     * 量高量低标志
     * @type {number}
     * @memberof PdaReadDataDto
     */
    highLowState?: any;
    /**
     * 是否估抄
     * @type {boolean}
     * @memberof PdaReadDataDto
     */
    isEstimate?: any;
    /**
     * 备注
     * @type {string}
     * @memberof PdaReadDataDto
     */
    readRemark?: any;
    /**
     * 抄表状态 0：未抄 1:已抄 2:已复核 3：已开账
     * @type {number}
     * @memberof PdaReadDataDto
     */
    recordState?: any;
    /**
     * 换表水量
     * @type {number}
     * @memberof PdaReadDataDto
     */
    replaceWater?: any;
    /**
     * 平均水量
     * @type {number}
     * @memberof PdaReadDataDto
     */
    avgWater?: any;
    /**
     * 量高系数
     * @type {number}
     * @memberof PdaReadDataDto
     */
    highCoefficient?: any;
    /**
     * 量低系数
     * @type {number}
     * @memberof PdaReadDataDto
     */
    lowCoefficient?: any;
    /**
     * 量高
     * @type {number}
     * @memberof PdaReadDataDto
     */
    highWater?: any;
    /**
     * 量低
     * @type {number}
     * @memberof PdaReadDataDto
     */
    lowWater?: any;
    /**
     * 数据状态 0 更新、添加。-1删除
     * @type {number}
     * @memberof PdaReadDataDto
     */
    dataState?: any;
}
