/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Pda欠费查询
 * @export
 * @interface PdaArrearageInputDto
 */
export interface PdaArrearageInputDto {
    /**
     * 开始年月
     * @type {number}
     * @memberof PdaArrearageInputDto
     */
    beginMonth?: number;
    /**
     * 结束年月
     * @type {number}
     * @memberof PdaArrearageInputDto
     */
    endMonth?: number;
    /**
     * 抄表员
     * @type {string}
     * @memberof PdaArrearageInputDto
     */
    meterReaderId?: string;
    /**
     * 册本编号
     * @type {number}
     * @memberof PdaArrearageInputDto
     */
    bookId?: number;
    /**
     * 组合查询条件
     * @type {string}
     * @memberof PdaArrearageInputDto
     */
    queryConditions?: any;
    /**
     * 
     * @type {number}
     * @memberof PdaArrearageInputDto
     */
    skipCount?: any;
    /**
     * 
     * @type {number}
     * @memberof PdaArrearageInputDto
     */
    maxResultCount?: any;
}
