/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 账单信息
 * @export
 * @interface PdaBillingInfo
 */
export interface PdaBillingInfo {
    /**
     * 账务年月
     * @type {number}
     * @memberof PdaBillingInfo
     */
    billMonth?: any;
    /**
     * 开账水量
     * @type {number}
     * @memberof PdaBillingInfo
     */
    billWater?: any;
    /**
     * 账单金额
     * @type {number}
     * @memberof PdaBillingInfo
     */
    extendedAmount?: any;
    /**
     * 违约金
     * @type {number}
     * @memberof PdaBillingInfo
     */
    lateFee?: any;
    /**
     * 欠费标志  0：欠费
     * @type {number}
     * @memberof PdaBillingInfo
     */
    payState?: number;
}
