/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 缴费记录
 * @export
 * @interface PdaPayRecord
 */
export interface PdaPayRecord {
    /**
     * 缴费时间
     * @type {string}
     * @memberof PdaPayRecord
     */
    payDate?: any | null;
    /**
     * 收费员
     * @type {string}
     * @memberof PdaPayRecord
     */
    cashier?: any | null;
    /**
     * 实缴金额
     * @type {number}
     * @memberof PdaPayRecord
     */
    actualMoney?: any;
    /**
     * 余额
     * @type {number}
     * @memberof PdaPayRecord
     */
    deposit?: any;
}
