/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Pda 抄表统计查询
 * @export
 * @interface PdaReadingCollectInput
 */
export interface PdaReadingCollectInput {
    /**
     * 抄表员
     * @type {string}
     * @memberof PdaReadingCollectInput
     */
    meterReadingId?: any;
    /**
     * 抄表年月
     * @type {number}
     * @memberof PdaReadingCollectInput
     */
    billMonth?: any;
}
