/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Pda欠费清单
 * @export
 * @interface PdaArrearageDto
 */
export interface PdaArrearageDto {
    /**
     * 客户Id
     * @type {number}
     * @memberof PdaArrearageDto
     */
    custId?: any;
    /**
     * 客户编号
     * @type {string}
     * @memberof PdaArrearageDto
     */
    custCode?: any | null;
    /**
     * 客户名称
     * @type {string}
     * @memberof PdaArrearageDto
     */
    custName?: any | null;
    /**
     * 客户地址
     * @type {string}
     * @memberof PdaArrearageDto
     */
    custAddress?: any | null;
    /**
     * 账单金额
     * @type {number}
     * @memberof PdaArrearageDto
     */
    totalExtendedAmount?: any;
    /**
     * 违约金
     * @type {number}
     * @memberof PdaArrearageDto
     */
    totalLateFee?: any;
    /**
     * 预存余额
     * @type {number}
     * @memberof PdaArrearageDto
     */
    deposit?: any;
}
