/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 收费查询
 * @export
 * @interface PdaPaymentCollectInput
 */
export interface PdaPaymentCollectInput {
    /**
     * 抄表员
     * @type {string}
     * @memberof PdaPaymentCollectInput
     */
    meterReaderId?: any;
    /**
     * 开始时间  yyyyMMdd
     * @type {number}
     * @memberof PdaPaymentCollectInput
     */
    beginDate?: any;
    /**
     * 结束时间  yyyyMMdd
     * @type {number}
     * @memberof PdaPaymentCollectInput
     */
    endDate?: any;
    /**
     * 组合查询条件
     * @type {string}
     * @memberof PdaPaymentCollectInput
     */
    queryConditions?: any;
    /**
     * 
     * @type {number}
     * @memberof PdaPaymentCollectInput
     */
    skipCount?: any;
    /**
     * 
     * @type {number}
     * @memberof PdaPaymentCollectInput
     */
    maxResultCount?: any;
}
