/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Pda权限
 * @export
 * @interface PdaUserPermissionDto
 */
export interface PdaUserPermissionDto {
    /**
     * 权限编码
     * @type {string}
     * @memberof PdaUserPermissionDto
     */
    code?: any | null;
    /**
     * 权限名称
     * @type {string}
     * @memberof PdaUserPermissionDto
     */
    name?: any | null;
    /**
     * 权限说明
     * @type {string}
     * @memberof PdaUserPermissionDto
     */
    description?: any | null;
    /**
     * 是否授权
     * @type {boolean}
     * @memberof PdaUserPermissionDto
     */
    isGranted?: any;
    /**
     * 是否禁用（已通过角色分配权限）
     * @type {boolean}
     * @memberof PdaUserPermissionDto
     */
    disabled?: any;
}
