/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 欠费查询-账单详情
 * @export
 * @interface PdaArrearageChargesInputDto
 */
export interface PdaArrearageChargesInputDto {
    /**
     * 开始年月
     * @type {number}
     * @memberof PdaArrearageChargesInputDto
     */
    beginMonth?: any | null;
    /**
     * 结束年月
     * @type {number}
     * @memberof PdaArrearageChargesInputDto
     */
    endMonth?: any | null;
    /**
     * 客户编号
     * @type {number}
     * @memberof PdaArrearageChargesInputDto
     */
    custId?: any;
}
