/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 移动端抄表-册本清单
 * @export
 * @interface PdaMeterBookDto
 */
export interface PdaMeterBookDto {
    /**
     * 账务年月
     * @type {number}
     * @memberof PdaMeterBookDto
     */
    billMonth?: any;
    /**
     * 册本编号
     * @type {number}
     * @memberof PdaMeterBookDto
     */
    bookId?: any;
    /**
     * 册本编码 创建由[Sequence]获取
     * @type {string}
     * @memberof PdaMeterBookDto
     */
    bookCode?: any;
    /**
     * 册本名称
     * @type {string}
     * @memberof PdaMeterBookDto
     */
    bookName?: any;
    /**
     * 抄表周期
     * @type {number}
     * @memberof PdaMeterBookDto
     */
    readCycle?: any;
    /**
     * 备注
     * @type {string}
     * @memberof PdaMeterBookDto
     */
    remark?: any;
    /**
     * 已抄数
     * @type {number}
     * @memberof PdaMeterBookDto
     */
    readingNumber?: any;
    /**
     * 应抄数
     * @type {number}
     * @memberof PdaMeterBookDto
     */
    totalNumber?: any;
}
