/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PdaPaymentCollectPagedResultDto } from "./pda-payment-collect-paged-result-dto";

/**
 * 收费统计
 * @export
 * @interface PdaPaymentCollectDto
 */
export interface PdaPaymentCollectDto {
    /**
     * 实际收费
     * @type {number}
     * @memberof PdaPaymentCollectDto
     */
    totalActualMoney?: any;
    /**
     * 实际销账
     * @type {number}
     * @memberof PdaPaymentCollectDto
     */
    totalSoldMoney?: any;
    /**
     * 
     * @type {PdaPaymentCollectPagedResultDto}
     * @memberof PdaPaymentCollectDto
     */
    paymentCollects?: PdaPaymentCollectPagedResultDto;
}
