/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 基础信息
 * @export
 * @interface PdaCustInfo
 */
export interface PdaCustInfo {
    /**
     * 客户名称
     * @type {string}
     * @memberof PdaCustInfo
     */
    custName?: any | null;
    /**
     * 客户地址
     * @type {string}
     * @memberof PdaCustInfo
     */
    custAddress?: any | null;
    /**
     * 营业站点
     * @type {string}
     * @memberof PdaCustInfo
     */
    orgName?: any | null;
    /**
     * 联系电话
     * @type {string}
     * @memberof PdaCustInfo
     */
    mobile?: any | null;
    /**
     * 人口数
     * @type {number}
     * @memberof PdaCustInfo
     */
    population?: any;
    /**
     * 缴费方式
     * @type {string}
     * @memberof PdaCustInfo
     */
    payMethod?: any | null;
    /**
     * 用户类型
     * @type {string}
     * @memberof PdaCustInfo
     */
    custType?: any | null;
    /**
     * 用水性质
     * @type {string}
     * @memberof PdaCustInfo
     */
    priceCode?: any | null;
    /**
     * 预存余额
     * @type {number}
     * @memberof PdaCustInfo
     */
    deposit?: any;
    /**
     * 年度使用量
     * @type {number}
     * @memberof PdaCustInfo
     */
    yearTotalWater?: any;
    /**
     * 当前底码
     * @type {number}
     * @memberof PdaCustInfo
     */
    reading?: any;
    /**
     * 安装位置
     * @type {string}
     * @memberof PdaCustInfo
     */
    installLocation?: any | null;
    /**
     * 钢印号
     * @type {string}
     * @memberof PdaCustInfo
     */
    steelMark?: any | null;
    /**
     * 水表口径
     * @type {string}
     * @memberof PdaCustInfo
     */
    caliber?: any | null;
    /**
     * 水表厂家
     * @type {string}
     * @memberof PdaCustInfo
     */
    producer?: any | null;
    /**
     * 换表日期
     * @type {string}
     * @memberof PdaCustInfo
     */
    replaceDate?: any | null;
    /**
     * 立户日期
     * @type {string}
     * @memberof PdaCustInfo
     */
    buildDate?: any | null;
}
