/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 抄表统计
 * @export
 * @interface PdaReadingCollectDto
 */
export interface PdaReadingCollectDto {
    /**
     * 册本编号
     * @type {string}
     * @memberof PdaReadingCollectDto
     */
    bookCode?: any | null;
    /**
     * 册本名称
     * @type {string}
     * @memberof PdaReadingCollectDto
     */
    bookName?: any | null;
    /**
     * 应抄数量
     * @type {number}
     * @memberof PdaReadingCollectDto
     */
    expectRead?: any;
    /**
     * 实抄数量
     * @type {number}
     * @memberof PdaReadingCollectDto
     */
    actualRead?: any;
    /**
     * 水量
     * @type {number}
     * @memberof PdaReadingCollectDto
     */
    totalWater?: any;
    /**
     * 金额
     * @type {number}
     * @memberof PdaReadingCollectDto
     */
    totalMoney?: any;
}
