/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 客户详情
 * @export
 * @interface PdaCustDetailsDto
 */
export interface PdaCustDetailsDto {
    /**
     * 客户编号
     * @type {number}
     * @memberof PdaCustDetailsDto
     */
    custId?: any;
    /**
     * 
     * @type {PdaCustInfo}
     * @memberof PdaCustDetailsDto
     */
    custInfo?: any;
    /**
     * 
     * @type {Array&lt;PdaReadingRecord&gt;}
     * @memberof PdaCustDetailsDto
     */
    readingRecords?: any;
    /**
     * 
     * @type {Array&lt;PdaBillingInfo&gt;}
     * @memberof PdaCustDetailsDto
     */
    billingInfos?: any;
    /**
     * 
     * @type {Array&lt;PdaPayRecord&gt;}
     * @memberof PdaCustDetailsDto
     */
    payRecords?: any;
}
