/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ReadingMonthDto
 */
export interface ReadingMonthDto {
    /**
     * BillMonth
     * @type {number}
     * @memberof ReadingMonthDto
     */
    billingMonth?: any;
    /**
     * 开始时间
     * @type {Date}
     * @memberof ReadingMonthDto
     */
    startDate?: any;
    /**
     * 结束时间
     * @type {Date}
     * @memberof ReadingMonthDto
     */
    endDate?: any;
}
