/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 抄表数据查询
 * @export
 * @interface ReadDataByBookIdsInput
 */
export interface ReadDataByBookIdsInput {
    /**
     * 设备号
     * @type {string}
     * @memberof ReadDataByBookIdsInput
     */
    deviceCode?: any;
    /**
     * 册本Id
     * @type {Array&lt;number&gt;}
     * @memberof ReadDataByBookIdsInput
     */
    bookIds?: any;
}
