/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SysSettingDto
 */
export interface SysSettingDto {
    /**
     * 参数分组
     * @type {string}
     * @memberof SysSettingDto
     */
    groupName?: string;
    /**
     * 参数名称
     * @type {string}
     * @memberof SysSettingDto
     */
    name?: string;
    /**
     * 参数编码
     * @type {string}
     * @memberof SysSettingDto
     */
    code?: string;
    /**
     * 参数当前值
     * @type {string}
     * @memberof SysSettingDto
     */
    value?: string;
    /**
     * 备注
     * @type {string}
     * @memberof SysSettingDto
     */
    remark?: string;
}
