/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 附件属性
 * @export
 * @interface TerminalFileDto
 */
export interface TerminalFileDto {
    /**
     * 文件类型 --文本、照片、视频等
     * @type {number}
     * @memberof TerminalFileDto
     */
    fileType?: any;
    /**
     * 文件名称
     * @type {string}
     * @memberof TerminalFileDto
     */
    fileName?: any;
    /**
     * 文件地址
     * @type {string}
     * @memberof TerminalFileDto
     */
    fileUrl?: any;
    /**
     * 是否删除
     * @type {boolean}
     * @memberof TerminalFileDto
     */
    isDeleted?: any;
}
