/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Pda日志上传
 * @export
 * @interface UploadMobileLogFileDto
 */
export interface UploadMobileLogFileDto {
    /**
     * 设备号
     * @type {string}
     * @memberof UploadMobileLogFileDto
     */
    deviceCode: any;
    /**
     * Pda日志
     * @type {Array&lt;MobileLogFileDto&gt;}
     * @memberof UploadMobileLogFileDto
     */
    logFiles?: any;
}
