/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Pda抄表数据上传
 * @export
 * @interface UploadReadingDateDto
 */
export interface UploadReadingDateDto {
    /**
     * 设备号
     * @type {string}
     * @memberof UploadReadingDateDto
     */
    deviceCode: any;
    /**
     * 抄表数据
     * @type {Array&lt;ReadingDateDto&gt;}
     * @memberof UploadReadingDateDto
     */
    readingDates: any;
}
