/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Pda附件上传
 * @export
 * @interface UploadReadingFileDto
 */
export interface UploadReadingFileDto {
    /**
     * 设备号
     * @type {string}
     * @memberof UploadReadingFileDto
     */
    deviceCode: any;
    /**
     * 抄表数据附件
     * @type {Array&lt;ReadingFileDto&gt;}
     * @memberof UploadReadingFileDto
     */
    readingFiles: any;
}
