version: '3.7'
services:
  server:
    image: jeremaihloo/code-push-server:5.7.1
    volumes:
      - codepush-data-storage:/data/storage
      - codepush-data-tmp:/data/tmp
      - ./config.js:/config.js
    environment:
      DOWNLOAD_URL: 'http://175.24.249.87:3000/download'
      MYSQL_HOST: '175.24.249.87'
      MYSQL_PORT: '3310'
      MYSQL_USERNAME: 'codepush'
      MYSQL_PASSWORD: '123456'
      MYSQL_DATABASE: 'codepush'
      STORAGE_DIR: '/data/storage'
      DATA_DIR: '/data/tmp'
      NODE_ENV: 'production'
      CONFIG_FILE: '/config.js'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1000M
      restart_policy:
        condition: on-failure
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    links:
      - 'db:db'
      - 'redis:redis'
  db:
    image: mysql:5.7.23
    volumes:
      - codepush-data-mysql:/var/lib/mysql
      - ./sql/codepush-all.sql:/docker-entrypoint-initdb.d/codepush-all.sql
    ports:
      - '3310:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'On'
  redis:
    image: redis:4.0.11-alpine
    volumes:
      - codepush-data-redis:/data
    ports:
      - '6388:6379'
volumes:
  codepush-data-storage:
  codepush-data-tmp:
  codepush-data-mysql:
  codepush-data-redis:
