kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume-mysql
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql/data"
