/* tslint:disable */
/* eslint-disable */
/**
 * 抄表系统 - Pda抄表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { SysSettingDtoListResultDto } from '../models';
/**
 * MobileSystemApi - axios parameter creator
 * @export
 */
export const MobileSystemApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取所有参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAppMobileSystemSettingsGet: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/app/mobileSystem/settings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MobileSystemApi - functional programming interface
 * @export
 */
export const MobileSystemApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取所有参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAppMobileSystemSettingsGet(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SysSettingDtoListResultDto>> {
            const localVarAxiosArgs = await MobileSystemApiAxiosParamCreator(configuration).apiAppMobileSystemSettingsGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MobileSystemApi - factory interface
 * @export
 */
export const MobileSystemApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 获取所有参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAppMobileSystemSettingsGet(options?: any): AxiosPromise<SysSettingDtoListResultDto> {
            return MobileSystemApiFp(configuration).apiAppMobileSystemSettingsGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MobileSystemApi - object-oriented interface
 * @export
 * @class MobileSystemApi
 * @extends {BaseAPI}
 */
export class MobileSystemApi extends BaseAPI {
    /**
     * 
     * @summary 获取所有参数
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MobileSystemApi
     */
    public apiAppMobileSystemSettingsGet(options?: any) {
        return MobileSystemApiFp(this.configuration).apiAppMobileSystemSettingsGet(options).then((request) => request(this.axios, this.basePath));
    }
}
